### ISSUE TITLE
User blocking

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey#1790]
RP/リアクションなどを拒否できる機能。連合的にもないと困る

**Comment by Siphonay** [comment]
I think that this issue is about a block feature according to translators, sorry if it's not, I can't actually speak japanese.

I am strongly in favor of a block feature. I think it is essential for the privacy and safety of users. I just started my Misskey instance for me and my friends and the lack of a block feature is understandably a dealbreaker for some. Muting is just not enough because muted people can still see your posts.

I hope a block feature gets added to Misskey soon. 

Thank you for the work you are doing on it, have a nice day

**Comment by tamaina** [comment]
#3035 has been merged!

**Comment by mei23** [comment]
現状のブロック実装は以下のような感じです
- フォロー解除/拒否は、実装済み
- ブロック相手を隠す機能は、ブロックではなくミュートでのみ可能
- ブロック相手から隠す機能は、未実装

ブロック相手から隠す機能は、以下のような機能
https://docs.joinmastodon.org/usage/privacy/#blocking
> The user won't see other people's boosts of you
> The user won't see you in public timelines
> If you and the blocked user are on the same server, the blocked user will not be able to view your posts on your profile while logged in.

**Comment by ibrokemypie** [comment]
Itd be great to have multiple options for the admin the remove other instances from theirs
1: Defederation, no posts from the admins instance go to the defederated instance, and no posts, reactions, replies etc from the defederated instance reach the admins
2: Block, no interaction (notes, reacts, renotes, replies) from the blocked instance reach the admins instance. outgoing information is unaffected
3: Mute, posts from the muted instance do not show on any timelines except home timelines for local users who have followed users from the muted instance. Users not following users on the muted instance do not see any notes, replies etc from the muted instance.
4: Nsfw, all content from the instance is automatically tagged as nsfw
