### ISSUE TITLE
IPFS-JS integration within the client

### ISSUE THREAD

**Issue by ghost** [misskey-dev/misskey#2184]
# Summary
IPFS has the potential of saving server hosts tons of money in image hosting (currently the biggest sinking cost for misskey).

The suggestion is to use [IPFS-JS]([https://github.com/ipfs/js-ipfs]) in the client as an alternative way to distribute image as making such will make it so the server isn't the only one serving the images.

It would be a very good way to save money in the long run.

Currently IPFS-JS is still in early alpha, it is probably not yet the good time to add the integration. When it will be, I'll get to work on it with discussion done.

**Comment by Arlodotexe** [comment]
js-ipfs has evolved into Helia, no longer in alpha or beta. Content addressing allows for true "interplanetary" apps (distributed instead of client-server), but just as well can be used for simple things like saving money on image hosting. 

As long as someone anywhere is willing to host (seed) the images to users, the users can help seed any images they've viewed to other users, massively reducing server load. Content addressing makes any ipfs content self-verifiable. 10/10 would recommend.
