### ISSUE TITLE
Closed browser / offline notifications not working

### ISSUE THREAD

**Issue by pwFoo** [misskey-dev/misskey#3228]
At the moment offline notifications not working? Don't know if it's browser or service-worker related, but it should work with closed browser (desktop Chrome/ Edge/ Firefox and Chrome for Android).

**Comment by pwFoo** [comment]
Working demo
https://webpushdemo.azurewebsites.net

**Comment by pwFoo** [comment]
@syuilo
Working demo
https://webpushdemo.azurewebsites.net

**Comment by mei23** [comment]
client 2.x 以降、sw.jsが404返してます。
After client 2.x, sw.js returns 404.

`
スコープ ‘https://example.com/’ の ServiceWorker の登録または更新に失敗しました: スクリプト ‘https://example.com/sw.2.0.11745.ja-JP.js’ の読み込みが状態 404 で失敗しました。
`
```
$ curl https://example.com/sw.2.0.11745.ja-JP.js
ENOENT: no such file or directory, stat '/home/misskey/misskey/built/client/assets/sw.2.0.11745.ja-JP.js'
```

```
$ ls -1 /home/misskey/misskey/built/client/assets/sw*
:
/home/misskey/misskey/built/client/assets/sw.1.0.11698.nl-NL.js
/home/misskey/misskey/built/client/assets/sw.1.0.11698.pl.js
/home/misskey/misskey/built/client/assets/sw.1.0.11698.pl-PL.js
/home/misskey/misskey/built/client/assets/sw.2.0.11733.js
/home/misskey/misskey/built/client/assets/sw.2.0.11740.js
/home/misskey/misskey/built/client/assets/sw.2.0.11745.js
```

**Comment by tamaina** [comment]
Offline notification and some functions provided by the service worker are "disabled" because its i18n needs to add some codes.  
(By 46a51addade571d3d00d2cbc92f94b51c78dc709 )

Syuilo says "[It's too much bother to support the service worker i18n.](https://misskey.xyz/notes/5bebd76e9519d60026ecf05e) [Is it possible the sercie worker script to read LocalStorage?](https://misskey.xyz/notes/5bebd76e9519d60026ecf05e) [No, it seems to be impossible](https://misskey.xyz/notes/5bebd89ae3137f002ef00b3d)" and he disable the service worker because [he has no motivation to support because safari unsupports offline notification](https://misskey.xyz/notes/5bebd6bae3137f002ef00a87).

**Comment by pwFoo** [comment]
@tamaina 
Thank you for the information regarding the discussion about service-worker!

So offline notifications not supported for Chrome / Edge / Firefox because Safari doesn't support it (yet)?

Without offline notifications I have to think about a move (back) to Mastodon, which supports offline notifications.

**Comment by tamaina** [comment]
@pwFoo Safari's unsupporting offline notifications is not why misskey is not supporting them. The only reason is that there is nobody to implement i18n of service workers because the way of i18n of misskey (without service workers and some functions) renewed.

**Comment by shynome** [comment]
hey, I want to know the browser offline notifications is working ? the issue last update time is 2018-11-14, today is 2019-05-26 , I want to know today it can work? what needs to be done to make it work?
