### ISSUE TITLE
1 weeks ago を 1 week ago に

### ISSUE THREAD

**Issue by AyaMorisawa** [misskey-dev/misskey#329]
1 months ago, 1 years ago も同様に 1 month ago, 1 year ago に

**Comment by 4ioskd** [comment]
I think this issue has already solved.

https://github.com/misskey-dev/misskey/blob/348a5f3d7c3d14ab80bb32f74b0b7ea4416629ba/locales/en-US.yml#L1086-L1088

**Comment by Johann150** [comment]
It is still missing for smaller time units, but this has to be solved using Crowdin.
https://github.com/misskey-dev/misskey/blob/348a5f3d7c3d14ab80bb32f74b0b7ea4416629ba/locales/en-US.yml#L1083-L1085
@robflop could you maybe take a look? I think the `_ago.weeksAgo` and `_ago.daysAgo` etc. phrases should be alike.

I don't think it would be necessary to do this for `_ago.secondsAgo` though, since it will be displayed as "just now" if it was only 1 second ago.

**Comment by robflop** [comment]
I've adjusted the strings on Crowdin, including the one for seconds. Having just one of them be different would bother me, even if it's not gonna make much of a difference. When I did the german translation I did those pluralized to begin with, so the issue isn't present there, fyi. Not sure about other languages.
