### ISSUE TITLE
Missing Translation for src/misc/get-note-summary.ts in Crowdin

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3695]
# Summary
The file is not available for translation in crowdin.
There are a number of user-facing strings in there that are solely in japanese, such as the count of files on a toot "つのファイル" on line 25

# Expected Behavior

Strings tranlatable on crowdin

**Comment by ibrokemypie** [comment]
related:
<img width="148" alt="image" src="https://user-images.githubusercontent.com/7827846/50345506-7ac38780-0583-11e9-98de-d209c57418b1.png">

**Comment by LouisNitag** [comment]
Do you think this is a good first issue? I do not master NodeJS, but if I can help with this :)

**Comment by rinsuki** [comment]
I think this to be a bit of heavy work, because (as far as I know) server-side i18n has not yet been implemented in this project, so We would have to write that process from scratch.

Also, I don't think the server knows what language to return as an API response. The language settings of the browser is sent when the API is requested, but the language set in the browser may be different from the language set in the WebUI.

**Comment by tamaina** [comment]
クライアントサイドは翻訳できるようになったしサーバーサイドは絵文字表現になったのでいいんじゃないかなと
