### ISSUE TITLE
Credential Based Authentication

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3749]
# Summary

Misskey currently only supports acquisition of accessToken either from the user opening their settings and finding it, or registering an app, generating a link, having user open that link in a browser, having them log in there and accept, then opening the original app with a callback.

Neither of these are ergonomical, especially for client apps. Mastodon (and pleroma) support getting their version of the access key using a username and password combination. By supporting this same functionality it would make it a lot easier to create and use apps/clients for misskey, both for users and developers. Simplifying the workflow as well as making it easier to integrate misskey into existing projects

**Comment by tamaina** [comment]
So you are talking about [Resource Owner Password Credentials Flow](https://tools.ietf.org/html/rfc6749#section-4.3), aren't you? However, this specification says we need not implement it in Misskey because it already provides other ways to authenticate and provide tokens. (Also note that Misskey's authentication method is not Oauth2.)

**Comment by ibrokemypie** [comment]
I hadnt seen that before, but that sounds right. The user provides the app woth their credentials which the app uses in a request to the server which returns the access key.

What other ways to authenticate other than the two I mentioned exist in misskey?

**Comment by Johann150** [comment]
Currently, Miauth is also available in addition to the above solution. I will close this in favour of #8262.
