### ISSUE TITLE
NSFW Field in note object

### ISSUE THREAD

**Issue by ibrokemypie** [misskey-dev/misskey#3784]
# Summary

Currently the note object returned by the api gives no indication on whether the note is sensitive/nsfw
It would be very useful to add an nsfw or sensitive boolean field to that object

# Environment

**Comment by tamaina** [comment]
Misskeyは画像ごとにNSFWを管理しているのでvery usefulではなさそう

**Comment by Johann150** [comment]
I don't think you can mark an entire note as sensitive in Misskey, as tamaina said. In addition to that, you may also want to check if the note has a content warning set (`cw` field on note objects).

Since Notes do not have the property of being sensitive by themself from Misskey's perspective I don't think it would make sense to compute this.
