### ISSUE TITLE
Allow remote content for pages

### ISSUE THREAD

**Issue by pwFoo** [misskey-dev/misskey#5134]
Embed remote sites (html, php) as page content for more flexibility.

**Comment by pwFoo** [comment]
If it's a security problem maybe implement for admin created / allowed pages only? To add content pages to the instance.

**Comment by Johann150** [comment]
I think this would be too much of a security issue or also responsibility issue since the admin may become responsible for embedded content in some jurisdictions if the remote content is changed

If you want you could put a link to an external website and people can decide for themselves if they want to go there or not.
