### ISSUE TITLE
トークやグループをMatrixで連合

### ISSUE THREAD

**Issue by u1-liquid** [misskey-dev/misskey#5538]
Related #2394
Related #5535
Relatex #7199
Conflict with #5534

## Summary

トークやグループ機能を[Matrix.org](https://matrix.org/)で連合させるのはどうでしょう
ActivityPubプロトコルと共存できるとこは確認済み; iro.moeはMisskeyサーバーである同時にMatrix-Synapseインスタンスです。

### Matrixとは
一言で言えば分散型のSlack
詳しくは https://wiki.matrix-jp.net/doku.php?id=what_is_matrix

**Comment by mei23** [comment]
> トークやグループ機能をMatrix.orgで連合させるのはどうでしょう

Matrixプロトコルを実装して連合させるという意味ですかね？

> トークやグループをMatrixに統合

統合ってなんですかね？

**Comment by u1-liquid** [comment]
> Matrixプロトコルを実装して連合させるという意味ですかね？

はい
> 統合ってなんですかね？

Integrationの意味ですね

**Comment by ssmucny** [comment]
Has any work been done on this issue or is it stale? I think this would be an great improvement to the chat system in Misskey. 

It could be part of a larger rework of chats since group chats are currently not possible to set up through the GUI.

I don't think we would want to implement the entire Matrix protocol. Just the server-server API to enable federation as a native bridge. Misskey can handle the client-server interactions using its existing API endpoints. More discussion would need to be had with how features in Misskey align with Matrix features and where there are discrepancies.

**Comment by ssmucny** [comment]
This would help to address https://github.com/misskey-dev/misskey/issues/8453 since chat messages don't federate with other ActivityPub servers very well.

**Comment by tamaina** [comment]
> Has any work been done on this issue

Nothing has done.

> I think this would be an great improvement to the chat system in Misskey.

I think so.

**Comment by tamaina** [comment]
グループ, トーク（チャット）廃止
