### ISSUE TITLE
Username link shows up as a card on Mastodon

### ISSUE THREAD

**Issue by chocological00** [misskey-dev/misskey#5560]
## 💡 Summary
Also look: https://github.com/tootsuite/mastodon/issues/12149

## 🙂 Expected Behavior
Links in the username should look like this:
![image](https://user-images.githubusercontent.com/36347199/67667217-70eb8b80-f9c1-11e9-8af2-85acccc730dc.png)
No card, and pale blue color

## ☹️ Actual Behavior
When mentioning Mastodon user from Misskey, it looks like this:
![image](https://user-images.githubusercontent.com/36347199/67667264-89f43c80-f9c1-11e9-9035-2fd43f8f5fde.png)
[link](https://madost.one/notes/7ypjtmeqnq)

It shows a preview card, and color is bright blue.

I know that this is not a Misskey *bug*, but it would still be nice to get this fixed here because Mastodon claimed that they have no intention to fix this on their side.

## 📌 Environment
Misskey 11.34.0 -> Mastodon 3.0.1

**Comment by chocological00** [comment]
Card fix is [here](https://gitlab.com/chocological00/misskey/commit/a5d5489c779f6bcc23a0d19b0d44355656bd9590) and temporary fix for bright blue link is [here](https://gitlab.com/chocological00/misskey/commit/6f12644e15758fc480b5a34b496acb87b975de74).

For the second fix, Mastodon expects the link in the username to be in `https://host/@username` form. [Relevant code here](https://github.com/tootsuite/mastodon/blob/master/app/javascript/mastodon/components/status_content.js#L49).

**Comment by rinsuki** [comment]
MEMO: link color issue is related to #2467

**Comment by rinsuki** [comment]
core of this issue is that Misskey doesn't use the user's url for mention links.

If Misskey uses the user's URL as a mention link, Mastodon should no longer get (and show) the card.

https://github.com/tootsuite/mastodon/blob/9762fe382c76fdff5281a94f484191a92d09eac7/app/services/fetch_link_card_service.rb#L85-L88

however, this issue is difficult to (completely) solve because of a design issue of Misskey database.

Here is where Misskey converts mentions into links:
https://github.com/syuilo/misskey/blob/7a94117d902d98bb77da148249c1aeae30d9570d/src/mfm/toHtml.ts#L137-L139

`mentionedRemoteUsers` come from here:
https://github.com/syuilo/misskey/blob/7a94117d902d98bb77da148249c1aeae30d9570d/src/services/note/create.ts#L386-L390

but this is stored as a plain string to DB, cant resolve url from this object.

Adding a URL property here will resolve the mention of future posts, but it will require a very large migration to handle existing posts.

Since it is not realistic to deal with existing posts, considering a large-scale server, only new posts are corrected for the time being.

<details>
<summary>日本語版 / Japanese version</summary>

この問題の核心は、Misskeyが`user.url`をメンションのリンク先に使わないことです。

もしMisskeyが`user.url`をメンションのリンク先にしていれば、Mastodonはカードを表示しないはずです。

https://github.com/tootsuite/mastodon/blob/9762fe382c76fdff5281a94f484191a92d09eac7/app/services/fetch_link_card_service.rb#L85-L88

ですが、この問題を(完璧に)解決するにはMisskeyのデータベースの設計の問題により困難です。

ここでMisskeyはリンクをHTMLに変換しています:
https://github.com/syuilo/misskey/blob/7a94117d902d98bb77da148249c1aeae30d9570d/src/mfm/toHtml.ts#L137-L139

この`mentionedRemoteUsers`はここから来ます:
https://github.com/syuilo/misskey/blob/7a94117d902d98bb77da148249c1aeae30d9570d/src/services/note/create.ts#L386-L390

ですが、ここではただの文字列としてDBに保存されているため、ここからURLを取ってくるのは困難です。

新しい投稿のメンションのリンク先を`url`にするのは簡単ですが、既存の投稿に対応するにはとても大きいマイグレーションが必要になります。

既存の投稿に対応するのは大規模のサーバーのことを考えると現実的ではないので、ひとまず修正後に作られる新しい投稿にのみ対応します。

</details>

**Comment by mei23** [comment]
まずここには2つの問題が記述されていて

問題1: メンションでカードが表示されてしまう
→ u-url を付ければなおる
https://github.com/tootsuite/mastodon/blob/9762fe382c76fdff5281a94f484191a92d09eac7/app/services/fetch_link_card_service.rb#L85-L88

問題2: メンションの色がブルーになってしまう
https://github.com/tootsuite/mastodon/blob/master/app/javascript/mastodon/components/status_content.js#L49

---

> この問題の核心は、Misskeyがuser.urlをメンションのリンク先に使わないことです。
> もしMisskeyがuser.urlをメンションのリンク先にしていれば、Mastodonはカードを表示しないはずです。

カードを表示しないようにするだけならば1に対応してu-urlを付けるだけでいいように思えます
Mastodon側でMisskey側で対応してと言ってるのも問題1だけです

---

問題2については 
> この問題の核心は、Misskeyがuser.urlをメンションのリンク先に使わないことです。

が仕様上問題があるとも思えないので
(mentionがuriだとメンション扱いのUIに出来ないのはMastodonの構造上の都合と思われる)
のでスキーマを変えてまで対応しなくていいのではと思います。

**Comment by rinsuki** [comment]
メンションの色がブルーになるだけじゃなく、WebUI内でプロフィールを開けない問題もあるので直したい気持ちが強い

**Comment by rinsuki** [comment]
URIはActivityPubだとhttpsなURLなはずだし、Mastodon側でURIでもmentionリンクとして処理すればいいというアレもあるかもしれないけど、それはそれとしてリンク先のhrefには`url`を用いたほうが親切な気がする (`url`は <q>A link to the actor's "profile web page", if not equal to the value of id. </q>なので https://www.w3.org/TR/activitypub/#as2-actor-properties )

**Comment by mei23** [comment]
> メンションの色がブルーになるだけじゃなく、WebUI内でプロフィールを開けない問題もあるので直したい気持ちが強い

この問題は、今はAP用URLの場合はAccepts見てリダイレクトするようになってるのでなおってます
https://github.com/syuilo/misskey/issues/2467#issuecomment-547122578

**Comment by rinsuki** [comment]
あーっそうじゃなくて、(Mastodon側でリンクがメンションで認識されないと)MastodonのWebUI内のプロフィールページで開けないという話
<img src=https://user-images.githubusercontent.com/6533808/67721104-15e58300-fa19-11e9-8da1-9f23cfadc435.gif height=384>

**Comment by mei23** [comment]
> urlを用いたほうが親切

それはある

検索バーで url が入力された場合 (ap/show API) に、1回フェッチして再度DB探索する必要がなくなるというのもある
https://github.com/syuilo/misskey/blob/245b08b624573cf4f6cb3192995d5d4f319cbce2/src/server/api/endpoints/ap/show.ts#L97-L102

**Comment by mei23** [comment]
> あーっそうじゃなくて、(Mastodon側でリンクがメンションで認識されないと)MastodonのWebUI内のプロフィールページで開けないという話

あー

https://docs.joinmastodon.org/api/entities/#status
API Entityのmentionsの中にハッシュタグやunhandledLinkを混ぜて返して
正当なメンションURLと発生するかもわからないunhandledLinkを判別するために
urlとだけマッチしてるMastodonが手抜きな気もするけど…
→あまりmentionsにメンション以外が入ってるパターン観測できないので過去互換？

**Comment by rinsuki** [comment]
> スキーマを変えてまで対応しなくていいのでは

このスキーマがDBのスキーマのことを指しているのであれば、`mentionedRemoteUsers`は<q>ただの文字列としてDBに保存されている</q>ので、新規投稿への対応だけだったらTypeScript側のinterfaceにちょっと`url?: string`みたいなのを付け足して保存処理でurlが取れたら付けるようにするぐらいで行ける

**Comment by mei23** [comment]
> 保存処理でurlが取れたら付けるようにするぐらいで行ける

可能なら取得して添付する部分はやっちゃっていいと思います
(カード自体には関係ないですが)

**Comment by rinsuki** [comment]
メンション扱いになればカードも取られなくなるはず

https://github.com/tootsuite/mastodon/blob/9762fe382c76fdff5281a94f484191a92d09eac7/app/services/fetch_link_card_service.rb#L85-L88

の`mention_link?(a)`がtrueになればカードの対象から外されて、その`mention_link?(a)`は`href`のリンク先がmentionsのどれかのアカウントのurlと一致したら (要はMastodonのWebUIのメンションリンク判定とやってること一緒) trueを返すので

**Comment by mei23** [comment]
はい
Mastodonがデファクトスタンダードなのがいまいち気に食わないってだけなので両方やればいいとおもいます

**Comment by mei23** [comment]
Person.urlって格納してたんですね...
Note.urlの方は格納してなかったのでそっちと勘違いしてました…
