### ISSUE TITLE
hubzilla public posts are shown as private notes

### ISSUE THREAD

**Issue by subpub** [misskey-dev/misskey#5767]
hubzilla is another fediverse network which additionally supports activitypub.  [Here](https://yuzulia.xyz/notes/816fd9495f30b4301cb8f1e7) the original  post is public but not visible. Mastodon side people can see it.

is this hubzilla's problem?

**Comment by mei23** [comment]
This should also happen in Mastodon.

Probably not the difference between Mastodon and Misskey, but depending on whether the post first came from Push or Pull.

Push: Someone is following Hubzilla users directly, and a post has been pushed from Hubzilla.
Pull: No one is following Hubzilla users, but was retrieved from Misskey because it was referenced in Reply and Renote.

In case of a post is retrieved by Pull, audience (visibility) is not specified in the object on Hubzilla side, so it will be treated as Private.
