### ISSUE TITLE
Deny registration if username is reserved

### ISSUE THREAD

**Issue by cliqsocial** [misskey-dev/misskey#5781]
## Summary

Allow instance admin to set a list of usernames as reserved so new user are not allowed to sign up if it matches any restricted username

example: admin, administrator, mod, moderator, user, username, etc.

**Comment by Johann150** [comment]
### (a) use `used_username` database table
A way to do this would be to use the `used_username` table, although that is not what it was meant for. It would stop people from registering specific names though. Since there are some users that Misskey itself may create, I think there should be some default entries in there too, namely `instance.actor` and `relay.actor`.
During the creation of these system users, the `used_username` table is also not checked, so that would work without problems.

For reserving other usernames, I don't know what the best method would be. I could imagine either another tool (in `src/tools`) or an additional setting and API in the instance configuration panel. Either way, doing this would require altering a database table to signal that the username was not actually used, but just reserved. The real purpose of `used_username` is to save user names that are active or were deleted so they are not reused; otherwise that could cause a mess with ActivityPub.

### (b) create an actual user
You could also create actual users and give them a really long random password so that it is practically impossible to log in to them. Then when you want someone to use that account, you can reset the password via Instance Settings > Users.

This would be the least technical solution, but would work right out of the box.
