### ISSUE TITLE
Sharing Preview Shows Avatar Instead Of Note

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#5964]
## 💡 Summary

Sharing link to note, the preview shows avatar instead of attachment

## 🙂 Expected Behavior

Show preview link with note thumbnail

## ☹️ Actual Behavior

Show preview link with user avatar

![misskey-thumbnail](https://user-images.githubusercontent.com/1679025/74619602-15761280-5104-11ea-9de7-c187d1ff9bba.jpeg)

## 📝 Steps to Reproduce

1. Share link to note
2. Go to note
3. Shows avatar

**Comment by okpierre** [comment]
@syuilo maybe something like WordPress or Twitter? 

Suggestion: show thumbnail of attached misskey post media if available and if not show user thumbnail - is that possible?

**Comment by syuilo** [comment]
This depends on your preference. I like avatars to be thumbnails even if they have attachments.

Please let us know what you think of everyone.

**Comment by okpierre** [comment]
Thumbnails give visitors a _preview_ of what each post is about. 

Just an example: 
`www.example.com/notes/3u8haf98` (sunset)
`www.example.com/notes/4jagh67w` (tiger)
`www.example.com/notes/s83kdys7` (food)

If I share WordPress link, then visitors will see thumbnail of
sunset
tiger
food

If I share Misskey link, then visitors will see thumbnail of
avatar
avatar
avatar

**Comment by EbiseLutica** [comment]
添付ファイルがあれば基本的にそれをプレビューに使用するのがogpとしては正しそう

**Comment by mei23** [comment]
埋め込みVideoプレイヤーを提供しようとした場合
https://github.com/misskey-dev/misskey/issues/8848

video thumbnail => avatar と fallback していくのが自然で
Play ボタンの後ろに avatar が表示されるのは結構不自然な感じ

**Comment by outloudvi** [comment]
> Please let us know what you think of everyone.

I think it would be great if the `og:image` can be the attached image (if any) instead of the avatar (like Twitter or Mastodon). I'll try to implement a setting toggle of it for my instance and check out a PR (if the maintainer is interested).

**Comment by Trif4** [comment]
When you link directly to a note, it's very often because you want to share an image or video with someone. The media is the main content of the note, not the text. And the avatar is certainly not the main content at all – after all, it's a link to a note, not a profile.

People are far more likely to click a link if they can see that it contains something interesting to them. By hiding the media in the preview, there's no way to tell what you'll see if you click the link, so many people will just ignore it. It would be great if Misskey could show attached media in the preview.

**Comment by outloudvi** [comment]
For this feature, I've been maintaining a patch over the [feat/i-5964](https://github.com/outloudvi/misskey/tree/feat/i-5964) branch of my fork. Instance maintainers who are interested may want to apply this.

(On that fork I've also built a solution to create patched Misskey Docker `web` images w/ GitHub Actions/GitHub Package Registry.)

**Comment by mappi-pr** [comment]
@outloudvi 
This is a great idea.
However, there is a concern that the NSFW file will be displayed on the destination site.
How about checking the "isSensitive" and "maybeSensitive" flags?

■note 
<img width="475" alt="image" src="https://github.com/misskey-dev/misskey/assets/75538777/0277552a-f651-46d6-99b9-9a1086028f8f">

■thumbnailUrl
<img width="682" alt="image" src="https://github.com/misskey-dev/misskey/assets/75538777/ba551a3f-4ae7-4beb-8c7b-4e672c78b200">

**Comment by outloudvi** [comment]
I've upgraded to 13.13.0 and it has updated to support such feature.

[Sample](https://mk.outv.im/notes/9fl64zevo1) preview with non-sensitive images:
![image](https://github.com/misskey-dev/misskey/assets/19144373/d53f616c-711d-4c88-9efd-dda7103fe4b4)

I noticed that the PR [tried to filter out sensitive images](https://github.com/misskey-dev/misskey/pull/10862/files#diff-3712b37156bacad5c87a326065b195dfaecd23248d7d111c1a0ebeb33e3f6316R8-R9) from the preview but I doubt it's working ([sample](https://mk.outv.im/notes/9bqhpw99hn)) - should be fixed by #10976:
![image](https://github.com/misskey-dev/misskey/assets/19144373/876a92cc-6627-48bd-9a2f-04592981dd55)

**Comment by samunohito** [comment]
#10976 にて既に実装済みのように見受けられますのでcloseいたします。
