### ISSUE TITLE
Unrestricted Private Message Submission Panel for Visitors Without Login/Sign Up 

### ISSUE THREAD

**Issue by Lakr233** [misskey-dev/misskey#6038]
uhh, I am currently learning Japanese but I haven't finished that あいうえお jobs so use English pls 🙏 

I want my visitor to be able to submit a message, this function should be unrestricted to anyone so I can get in touch with them.

I have also created a preview using Chrome's "F12" and the screenshot is below, have a look tho.

![截屏2020-02-20下午7 18 23](https://user-images.githubusercontent.com/25259084/74929091-c686f080-5415-11ea-89d5-33898799c18b.png)

**Comment by rinsuki** [comment]
How do admin reply to messages coming from it? Isn't it enough to write the email address of an administrator?

**Comment by Lakr233** [comment]
> Isn't it enough to write the email address of an administrator?

Not everybody likes to write an email or it is just too many steps to log in to their email. I found my self wasting too much time on social media, so I want to uninstall my Twitter/Facebook while keeping people a way to reach me out more easily. Click on that link I left, and then submit any important information/message there easily. They can leave an email or a phone number in their message so I can reply to them in that way.

> Isn't it enough to write the email address of an administrator?

Email is always full of verification and rubbish that I don't want to check them. I don't want wasting time log in to my 10x email accounts and then searching for useful information in that sea if there really is some.

It would be a better world to have that feature.

**Comment by Johann150** [comment]
I think this is not a good feature to have. Another reason against it is that it could easily be abused for spamming the administrator or moderators. I also think that email is a better idea for this as there are already existing spam filters for it and so on.

I can also not understand why it would be too cumbersome to write an email. If you are annoyed by logging in to a website every time, you could use a program on your computer instead. To me it sounds like the real problem is that your email mailbox is unorganized.
