### ISSUE TITLE
webhook api

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#6332]
## Summary

なんらかのイベントが発生すると、MisskeyサーバーからHTTPリクエストを指定したサーバーに送信する
サードパーティアプリケーションでMisskeyの通知機能を実装するときなどに有用と思われる
現時点でもsw/register APIを使って同等のことは出来るが、これはサードパーティから利用されることを想定していない

**Comment by Johann150** [comment]
<ol>
<li>Since I am not familiar with Service Worker, I would be interested to know why this is not intended for 3rd party use.
<li><details>
<summary><del>authentication</del></summary>

~~Different variants exist for each provider, and it does not seem to be standardized.~~ I saw that the linked PR already contains provisions for authentication using a shared secret.
I think we could make use of the existing infrastructure of using HTTP signatures to prove the authenticity of webhook requests, just like delivering activitypub requests. This could be done with the `@instance.actor` keys, they can easily be retrieved like this:

```sh
$ curl -H 'accept: application/activity+json' https://misskey.io/@instance.actor
```
will return the activitypub actor data like this:
```js
{
  //...
  "publicKey":{
    "id":"https://misskey.io/users/8xg6igguzx#main-key",
    "type":"Key",
    "owner":"https://misskey.io/users/8xg6igguzx",
    "publicKeyPem":"-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAnzXBSB0hQFL4YcWrV00A\nW+Vg0LErgzpqyQSa2KdXMe9KsRojDfCN7jpfGhEG6dILzSmfA/FvXuGkIbiRdmne\n0K/w2uUNbI0gfzxSvS2XMGBeQ927OPWm8LvkqMc5S5JXflReAKjmwHZydxFKIWUH\ns72eX1tcDupgvOZvLJ+ZmDeylATo+n6ZkTgIEPkneCrC15z2rEoDvb+pSEtEyNKy\noXM6+keogz3F7RQ0+IOc+tmPOKXFVYaPiHBuroCidNjNXwZ6N15wTB5lEOrguM28\nutupI8vHH005sxWd9FVyyyrzITpbCyTfP7Y3IwZopS/VJNuBvKQ+oLTM9QQQwse5\nvYNYuCCjMIWm3pEWKCvi7XPEm36ygo5SQRYNh+YOz6+4Qyy+bvO0ETOOvbzL8Af9\njXekilZADMn68E0bGF+iTnkMZw3xd1YUaWAIn//9vAPLNusC+p77xyp2+RKQsw8Q\n/i68oWpmL/gmCpVUpzFnA5TABAZG8m7+bEMht0Ir8uCxF9yL7ilPgTJoBq+wSgIc\nsEqjm1kUSutdQlml+jdc3SqpkBD/bmct+Eli7en7j49uF1KB0Au70pstm30SocMW\nDSOdspRl0UGUuMj2v7szd/FywpvbG2xuzBmJMr/KuYPj3f1wTszD1L2D8+pgcYlJ\nZ+mdv6xNhDPcrgo3r50wJ8UCAwEAAQ==\n-----END PUBLIC KEY-----\n"
  }
  //...
}
```
</details>
<li> I suggest that we handle response code <code>410 Gone</code> by deleting the registered webhook to avoid making unnecessary requests in the future, because 410 means the webhook URL <i>would never come back</i>, so it does not make sense to keep it.
<li> It might be interesting to add the ability to enable and disable a webhook, without having to delete it. This is interesting because it would also allow Misskey to automatically disable a webhook:
<ul>
    <li>if specific status codes are sent that indicate a more permanent problem. maybe for example <code>405 Method not allowed</code>
    <li> if too many requests fail in a row &rarr; keep track of response codes and failure counts in Redis? could show last response code as convenience for developers
</ul>

**Comment by syuilo** [comment]
> It might be interesting to add the ability to enable and disable a webhook, without having to delete it.

This is already implemented in https://github.com/misskey-dev/misskey/pull/8457

**Comment by syuilo** [comment]
> I suggest that we handle response code 410 Gone by deleting the registered webhook

👍

**Comment by syuilo** [comment]
> Since I am not familiar with Service Worker, I would be interested to know why this is not intended for 3rd party use.

It is not designed for any other use, as it literally handles events for ServiceWorker push notifications.
