### ISSUE TITLE
New threaded replies break on long threads

### ISSUE THREAD

**Issue by matrix07012** [misskey-dev/misskey#6343]
## 💡 Summary

I love the new threaded replies, but it appears that they don't stop even when outside the viewport. An example would be https://catgirl.life/notes/83msoy88v8

## 🙂 Expected Behavior

Stop threading when thread starts leaving the view port with a indication that the thread continues. Maybe allow users to change size of the viewport. 

![Screenshot 2020-05-10 13 19 22](https://user-images.githubusercontent.com/8049717/81497818-4740e480-92c1-11ea-9c8f-6cea0cd2ed37.png)

## ☹️ Actual Behavior

![image](https://user-images.githubusercontent.com/8049717/81497686-48bddd00-92c0-11ea-86fd-2945adcd6aa1.png)

## 📝 Steps to Reproduce

1.Make a really long thread

## 📌 Environment

Misskey v12.37.0

**Comment by Johann150** [comment]
I think the easiest solution would be that the client stops rendering other notes after a specified depth to the currently selected note and instead puts a link like "continue this thread" which leads to the note that would be put there otherwise. I think it would be easier than checking things about the viewport and would also solve the issue where the entire note is squished very narrow.
