### ISSUE TITLE
Incorrect Peer Dependency

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#6494]
## 💡 Summary

List of incorrect peer dependency

## 🙂 Expected Behavior

No errors about dependencies

## ☹️ Actual Behavior

```
warning " > css-loader@3.6.0" has incorrect peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > eslint-plugin-vue@6.2.2" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
warning " > json5-loader@4.0.0" has incorrect peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > sass-loader@8.0.2" has incorrect peer dependency "webpack@^4.36.0 || ^5.0.0".
warning " > style-loader@1.2.1" has incorrect peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > tslint-sonarts@1.9.0" has incorrect peer dependency "tslint@^5.11.0".
warning " > url-loader@4.1.0" has incorrect peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "webpack > terser-webpack-plugin@3.0.6" has incorrect peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > webpack-cli@3.3.12" has incorrect peer dependency "webpack@4.x.x".
```

## 📝 Steps to Reproduce

1. checkout to latest master
2. follow official upgrade instructions

## 📌 Environment

Misskey 12.40.0

**Comment by hinaloe** [comment]
Not a bug. They are warnings, not errors.

| package | reason |
|:----:|:----|
| webpack | misskey is using beta (next) version of webpack (now, `5.0.0-beta.22`). That is developing and not match with `^5.0.0` ([detail](https://semver.org/#spec-item-11)). |
| eslint-plugin-vue | that support eslint v7 since [v7.0.0-alpha.2](https://github.com/vuejs/eslint-plugin-vue/releases/tag/v7.0.0-alpha.2), but not stable released. |
| tslint-sonarts | *This package has been deprecated* (recommended to use [eslint-plugin-sonarjs](https://www.npmjs.com/package/eslint-plugin-sonarjs) with eslint) |
