### ISSUE TITLE
脱FontAwesome

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/misskey#6511]
## Summary

- FontAwesomeは無料で使えるものが少ない
- (無料だと)デザインがあまり好みではない

**Comment by Simirall** [comment]
Material iconsとか https://material.io/resources/icons/
> Our icons are free for everyone to use.
> Available under Apache license version 2.0.

**Comment by EbiseLutica** [comment]
以前使ってみたことあるけど、Material Icons のほうが語彙が少なかった

**Comment by Simirall** [comment]
Syuilo Icon Font🧐

**Comment by syuilo** [comment]
これとか
https://fonts.google.com/icons

**Comment by rinsuki** [comment]
それ中身 Material Icons だよ

**Comment by syuilo** [comment]
おっと失礼

**Comment by kazukyakayashi** [comment]
Why not https://forkaweso.me/ (License: SIL OFL 1.1, Open Font License) ?

Or : 
- https://feathericons.com/ (MIT license)
- https://tablericons.com/ (MIT license)

**Comment by acid-chicken** [comment]
> あと重め

これってアイコンのレンダリング負荷の話？あるいはレンダリングのみに限らないライブラリの動作コストとか、アセットサイズのことを指している？

**Comment by tamaina** [comment]
> アセットサイズ

Tree Shakingしてるしほかのライブラリにしたとしても減るかしら？

**Comment by syuilo** [comment]
> > あと重め
> 
> これってアイコンのレンダリング負荷の話？あるいはレンダリングのみに限らないライブラリの動作コストとか、アセットサイズのことを指している？

どっちもかな
ひとつひとつがVueのコンポートになっているから多少なりともレンダリングコストが発生するし、バグか知らんけどTreeShakingとかCodeSplittingが何故か効かない(DynamicImportでしか読み込まれないファイル内であるアイコンをImportしていても、アイコンだけ何故かメインのバンドルに含まれる)

**Comment by syuilo** [comment]
後これは気持ちの問題だけどできれば完全にオープンソースなもの使いたい

**Comment by syuilo** [comment]
https://css.gg/app
もある

**Comment by syuilo** [comment]
MaterialIcons使う方向で進めている

**Comment by syuilo** [comment]
やっぱり https://github.com/tabler/tabler-icons が良さそう

**Comment by syuilo** [comment]
やっていくか

**Comment by ThatOneCalculator** [comment]
Thoughts on https://phosphoricons.com/ ? (+ https://github.com/phosphor-icons/phosphor-vue)

**Comment by syuilo** [comment]
> Thoughts on https://phosphoricons.com/ ? (+ https://github.com/phosphor-icons/phosphor-vue)

cool

**Comment by Johann150** [comment]
I think an issue we should also consider is that it will be confusing if the look of the icons changes. In some places this might be okay because there is also text next to the icon, but in some places (e.g. Top Menu in Classic UI) there is just the icon.

I am not sure if it is really necessary (and also worth the big effort) to switch icon sets.

**Comment by ThatOneCalculator** [comment]
Phosphor has (almost) all the icons that Misskey currently uses, so I don't think it's too big of an issue

**Comment by Johann150** [comment]
My concern is more that the icons will just *look different* not whether the icon set has icons with the same name.

Take for example the "follow requests" button. It currently looks like this: 
![icon of user with a clock](https://user-images.githubusercontent.com/20990607/174850245-6c667b90-99ea-44a7-969f-50af4d2c4985.png)
I'm not sure what Phosphor icon you would want to replace it with, because I could not find a similar icon. Maybe `user-circle-gear`?
<img alt="person in a circle with gear" src="https://user-images.githubusercontent.com/20990607/174850848-45849744-a0e6-4d2e-be58-957760c5d1c7.png" height="50"/>
But as you can see, the icons are quite different. If I am looking in my menu bar and looking for a specific icon because I know what it used to look like, I will be confused because I can not find it.

**Comment by ThatOneCalculator** [comment]
>  I'm not sure what Phosphor icon you would want to replace it with, because I could not find a similar icon. Maybe user-circle-gear?

More likely `user-gear` or `user-list`, but I get where you're coming from. I still think it's a good idea to switch away from FA, but maybe polling the community about some ideas would be good

![image](https://user-images.githubusercontent.com/44733677/174852032-bd4ea055-0807-4b87-be8e-f44c92fc57fe.png)

**Comment by syuilo** [comment]
I prefer tabler icons for the way the corners are represented.
![image](https://user-images.githubusercontent.com/4439005/175526571-47f15f8d-3233-4b69-848c-2c35020a99a3.png)

**Comment by syuilo** [comment]
> My concern is more that the icons will just look different not whether the icon set has icons with the same name.

Conversely, there are cases where Fontawesome does not have appropriate icons, but Tabler/Phosphor icons do. (e.g. icon for webhook)
