### ISSUE TITLE
Cant open profile. Error [object Object]

### ISSUE THREAD

**Issue by RaZZlom** [misskey-dev/misskey#6769]
## 💡 Summary

When i try to open profile https://gentoo.live/sathariel i have error [object Object]

levels.error

`[api] Internal error occurred in ap/show: invalid json response body at https://gentoo.live/sathariel reason: Unexpected token < in JSON at position 0`

levels.warning

`[api] failed to resolve remote user: Error: invalid person: invalid name`

Nickname - :unicursalpink: Sathy de los Muertos 3: La venganza :chaos_pink:

## 🙂 Expected Behavior

Profile opened.

## ☹️ Actual Behavior

When i search @sathariel@gentoo.live

![2](https://user-images.githubusercontent.com/73530026/97299798-94f8db80-1866-11eb-843f-834a9fd63b8e.png)

When i search https://gentoo.live/sathariel

![3](https://user-images.githubusercontent.com/73530026/97299879-b5c13100-1866-11eb-9b0d-36738c2482b3.png)

## 📝 Steps to Reproduce

1. Click Search button.
2. Paste https://gentoo.live/sathariel or @sathariel@gentoo.live

## 📌 Environment

Debian GNU/Linux 10 (buster) x86_64
Misskey v12.50.0
Node.js v14.13.1
PostgreSQL v13.0 (Debian 13.0-1.pgdg100+1)
Redis v5.0.3

**Comment by rinsuki** [comment]
In `https://gentoo.live/sathariel`, gentoo.live doesn't providing ActivityPub object, so this is `gentoo.live` (or Pleroma) side issue. you can use `https://gentoo.live/users/sathariel` for search instead of `https://gentoo.live/sathariel`.

```sh
$ curl -vH "Accept: application/activity+json" https://gentoo.live/users/sathariel 2>&1 | grep -i content-type
< content-type: application/activity+json; charset=utf-8
< x-content-type-options: nosniff
$ curl -vH "Accept: application/activity+json" https://gentoo.live/sathariel 2>&1 | grep -i content-type 
< content-type: text/html; charset=utf-8
< x-content-type-options: nosniff
```

In `@sathariel@gentoo.live`, it is rejected by `Error: invalid person: invalid name`.
this error message becomes here:
https://github.com/syuilo/misskey/blob/9855405b8989713b81709fc1700e2ead97423467/src/remote/activitypub/models/person.ts#L61-L65
and `Users.validateName` is this:
https://github.com/syuilo/misskey/blob/9855405b8989713b81709fc1700e2ead97423467/src/models/repositories/user.ts#L304
...so, `@sathariel@gentoo.live`'s current name is `:unicursalpink:  Sathy de los Muertos 3: La venganza  :chaos_pink:`, it length is 66, so too long for misskey.

**Comment by RaZZlom** [comment]
Ok, i got it.

It turns out to correct the length of the name not so difficult task, right?

I hope you can fix it quickly.

Thank you.

**Comment by syuilo** [comment]
ActivityPubの仕様で名前の最大の長さは明示されているんだろうか？

**Comment by mei23** [comment]
少なくともActivityPubにはないはず

**Comment by mei23** [comment]
Mastodonはリモートから来たものはいくらでも大丈夫そうな気がする
とりあえずリモートから来たものはスキーマいっぱいの128文字とかでいいかも
