### ISSUE TITLE
Multiple Reactions Showing 

### ISSUE THREAD

**Issue by okpierre** [misskey-dev/misskey#6805]
## 💡 Summary

Reactions show duplicates instead of single one for each

![misskey-multiplereactions](https://user-images.githubusercontent.com/1679025/98132083-fda90f00-1e89-11eb-83c8-5aa5b0912dd6.png)

## 📌 Environment

Misskey v12.53.0

**Comment by Johann150** [comment]
I think this is intentional. The top one shows the Twemoji style emoji, the bottom shows the OS style emoji. If it is a custom emoji, the bottom one shows the name of the emoji.

https://github.com/misskey-dev/misskey/blob/fc65190ef7b687650018cccfee2219bf00827f70/src/client/components/reactions-viewer.details.vue#L5-L6

**Comment by tamaina** [comment]
仕様です
