### ISSUE TITLE
Umlauts in URL break URL convert to link

### ISSUE THREAD

**Issue by fabiscafe** [misskey-dev/misskey#6815]
## 💡 Summary

If you put an URL to misskey, misskey translates the URL by itself into a clickable link. If however the URL contains an umlaut (ä,ö,ü,)(which is pretty common in german-language areas), this process will stop and the clickable URL will only be everything before the umlaut. (and results in a broken link, of course)

## 🙂 Expected Behavior

It should also include umlauts

## ☹️ Actual Behavior

The URL gets translated into a broken Link. See here:
https://misskey.io/notes/8eak0jmwtr

## 📝 Steps to Reproduce

1. Post something that contains a URL with an Umlaut, like: https://www.dw.com/de/unesco-welterbe-gehört-kölns-jüdisches-viertel-bald-dazu/a-55522156

## 📌 Environment

Everywhere, on every instance I know of

**Comment by mei23** [comment]
Basically, umlaut needs to be URL-encoded.

If you want to write without URL encoding, use the `<URL>` syntax.
For example: `<https://www.dw.com/de/unesco-welterbe-gehört-kölns-jüdisches-viertel-bald-dazu/a-55522156>`

**Comment by syuilo** [comment]
In fact, URLs containing umlaut are not the correct URLs. Due to the specifications, only a limited number of characters can be used in the URL, simply put, only alphabets, numbers and some symbols can be used.
The reason the URLs appear to contain umlaut is that the browser interprets the encoded umlaut and restores it to its original form. This means that although the URLs appear to be able to use umlaut, the actual URLs do not contain umlaut. In fact, if you copy the URL in the example, it is "https://www.dw.com/de/unesco-welterbe-geh%C3%B6rt-k%C3%B6lns-j%C3%BCdisches-viertel-bald-dazu/a-55522156".
So it is not a problem with Misskey, it is a problem with the browser or user generating the umlautic URLs.

Translated with www.DeepL.com/Translator (free version)

**Comment by mei23** [comment]
... I thought, but the situation may be a little different because it comes from the remote and is embedded in the href on the AP
```
<a href="https://www.dw.com/de/antisemitismus-für-anfänger-ein-cartoon-buch/a-55512867?maca=de-rss-de-all-1119-rdf" rel="nofollow noopener noreferrer" target="_blank">
```

**Comment by mei23** [comment]
hrefに入ってるなら、ローカルの`<URL>`構文と同じように考慮していいかも
