### ISSUE TITLE
Unable to disable color stripe - many complaints

### ISSUE THREAD

**Issue by cliqsocial** [misskey-dev/misskey#6983]
## 💡 Summary

Unable to disable color stripe. We are getting many complaints. 

## 🙂 Expected Behavior

How can we disable the color stripes for all accounts?

reference: https://cliq.social/notes/8fq8wvh64d

## 📌 Environment

12.63.0

**Comment by syuilo** [comment]
I could not understand the meaning of "color stripe" in the reference. Can you please explain in detail?

**Comment by tamaina** [comment]
https://cliq.social/notes/8gssctby23

なるほど

**Comment by rinsuki** [comment]
instance ticker のことね

**Comment by syuilo** [comment]
これが効かないってことかな
![F0BCDFB6-C3B2-4FCE-A58A-BACF76F3501A](https://user-images.githubusercontent.com/4439005/104083332-1fa38100-5281-11eb-969b-eb32d0ab68ce.jpeg)

**Comment by tamaina** [comment]
いや、設定項目が見つけられてないんだと思う

あとインスタンスデフォルトで無効にしたいらしい

**Comment by rinsuki** [comment]
たしかにわかりづらいよねこれ

**Comment by syuilo** [comment]
各種設定値のインスタンスデフォルト値定義機能は計画してるけど実装はまだ先になりそう

**Comment by syuilo** [comment]
↑が実装されるまではフォークしてソースいじるとか

**Comment by syuilo** [comment]
> The color stripes are called the instance information or the instance ticker. To disable instance information on the user side, find `Settings` - `Client settings` - `General` - `Instjce information for notes` and select `Never show` instead of 'Show for remote users'.
Default user settings by the instance haven't implemented on Misskey yet but you can set default setting **changing the source code**, in this case you can change [store.ts#l155~](https://github.com/syuilo/misskey/blob/develop/src/client/store.ts#L155) to 'none' instead of 'remote'. It should be noted that this changing affects only for new users.

https://c2.a9z.dev/notes/8gsszmixmb
