### ISSUE TITLE
クリップの解除ができない

### ISSUE THREAD

**Issue by futchitwo** [misskey-dev/misskey#7020]
Removing clipped notes

## 💡 Summary

任意のノートのクリップを解除する方法がない。
間違ってクリップしてしまった場合などに必要。

## 🙂 Expected Behavior

任意のクリップを解除できる

## ☹️ Actual Behavior

クリップが解除できない

## 📌 Environment

Misskey 12.63.0

**Comment by futchitwo** [comment]
これ @syuilo にアサインされてるけどやってみていいかな
 syuilo も忙しそうだし

**Comment by tamaina** [comment]
しゅいろからアサイン外した

**Comment by syuilo** [comment]
🙏

**Comment by syuilo** [comment]
どのようなUIにするかが考えどころ

**Comment by futchitwo** [comment]
ノートメニューのクリップの項目から、クリップに含めるときと同じ操作をすると`すでにクリップされていますが解除しますか`的なダイアログとともにクリップ解除
（本当はクリップ名とともにノートがそれぞれのクリップに含まれているかを表示できればいいんだけど、APIの変更いりそう）


あとはクリップ一覧ページにいるときにはノートメニューのトップにでもクリップ解除ボタンを出せたらいいんだけど難しいかな

クリップ一覧にクリップ解除モードみたいなのをつけるのもあり

**Comment by syuilo** [comment]
> あとはクリップ一覧ページにいるときにはノートメニューのトップにでもクリップ解除ボタンを出せたらいいんだけど難しいかな

やろとしたらこれなんだよね
クリップ一覧ページでクリップ情報をprovideして、noteコンポーネントでinjectしてよしなに処理するとか

**Comment by tamaina** [comment]
メニューから「編集」を選択すると各ノートの左側にチェックマークが出現する→どこか（メニュー内？）に削除ボタンを設置して、それを押すとチェックした投稿がクリップから削除される

的な感じのUIを想像した

**Comment by syuilo** [comment]
> クリップ一覧にクリップ解除モードみたいなのをつけるのもあり

> メニューから「編集」を選択すると各ノートの左側にチェックマークが出現する→どこか（メニュー内？）に削除ボタンを設置して、それを押すとチェックした投稿がクリップから削除される

実装が少し複雑になりそう
あとパフォーマンス上の懸念も少しある

**Comment by futchitwo** [comment]
> メニューから「編集」を選択すると各ノートの左側にチェックマークが出現する→どこか（メニュー内？）に削除ボタンを設置して、それを押すとチェックした投稿がクリップから削除される

メニュー内に削除ボタン付けるなら編集モードはいらないと思う

**Comment by tamaina** [comment]
> メニュー内に削除ボタン

ノートのメニューじゃなくてクリップのメニュー

**Comment by tamaina** [comment]
編集モード（チェックボックスが表示される間）でないと削除ボタンは表示されないので編集ボタンは必要

**Comment by Johann150** [comment]
I'm not sure if notes can be added to a clip more than once. Otherwise the existing clip menu entry on notes could have toggle entries which clip a note or unclip it if it is already contained.
But I think it would be necessary to know to which clip the note is attached, which would require an API change and might be bad for server performance.
But it would improve UX especially when trying to unclip a note when it was clipped by mistake because you would not have to go into the clip to unclip.
