### ISSUE TITLE
Ability to use Mastodon/Pleroma apps?

### ISSUE THREAD

**Issue by ScootRay** [misskey-dev/misskey#7219]
Forgive me if this has been brought up before. I am wondering if it would be possible to tweak Misskey so that it can use the many Mastodon mobile apps already out there. For instance, Pleroma allows you to use/login-to Mastodon apps.

Would such a thing be possible with Misskey and expand it's universe of apps for users?

Thanks!
Ray

**Comment by syuilo** [comment]
APIに互換性を持たせることは、メンテナンスコストが大きくなるので難しいと思います。また、MastodonやPleromaとは機能的差異が大きいので(リアクションなど)、全てのMisskeyの機能が使えるようになるわけではありません。そのようなMisskeyの特徴的な機能が使えなければ、Misskeyを使用する意味はあまりないでしょう。

I think it would be difficult to make the APIs compatible, because the maintenance cost would be significant. Also, not all Misskey features will be available, since there are large functional differences from Mastodon and Pleroma (reactions, etc.). If you can't use such unique features of Misskey, there is not much point in using Misskey.

**Comment by ScootRay** [comment]
Ah, I understand. Thank you for making beautiful software, Misskey is stunning to use. 

Ray

**Comment by acid-chicken** [comment]
Related to #1280
